### ISSUE TITLE
Can not see the persons name who you are feedbacking

### ISSUE THREAD

**Issue by kvebers** [42-Heilbronn/True-Feedback#11]
In case of multiple evaluations, you can not see the persons name who you are feedbacking.

<img width="455" alt="Screen Shot 2023-08-11 at 11 03 04 AM" src="https://github.com/42-Heilbronn/True-Feedback/assets/49612380/c1ddf799-18fd-46d9-8d24-125472d649c9">

<img width="400" alt="Screen Shot 2023-08-11 at 11 07 15 AM" src="https://github.com/42-Heilbronn/True-Feedback/assets/49612380/5affa3fa-1b74-42ac-9e21-383821117058">

**Comment by Lacusch** [comment]
#12 Possible fix

**Comment by eschirni** [comment]
Will be available with the next release
![image](https://github.com/42-Heilbronn/True-Feedback/assets/62961896/7a57c0ad-b067-47f4-898f-2c107c6c66dd)
![prev](https://github.com/42-Heilbronn/True-Feedback/assets/62961896/dc5c3695-2a9f-47fb-943d-2fef755ea44f)
