### ISSUE TITLE
Remove missing feedbacks after request or duration

### ISSUE THREAD

**Issue by Alphacharge** [42-Heilbronn/True-Feedback#14]
there should be a cross to remove this message if i don't want to give an additional feedback to clear my evaluations list.
optional it could be a timer after 1 week.
<img width="631" alt="Screen Shot 2023-08-28 at 11 07 47 AM" src="https://github.com/42-Heilbronn/True-Feedback/assets/94354053/b16b1d85-0750-4ff3-ad74-80feb545f31f">

**Comment by Bluegales** [comment]
I think a timer would be preferred, since the intra behaves in the same way.

**Comment by eschirni** [comment]
We can make make a timer and a cross, so that if you install the extension for the first time, you won't be spammed with evals of the past and can decide not to give any feedback
